import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }: any) {
   return (
      <html lang="pt-br" suppressHydrationWarning>
         <body className="outfit.className">
            <ThemeProvider attribute="class" defaultTheme="light">
               <Header />
               {children}
               <Footer />
            </ThemeProvider>
         </body>
      </html>
   );
}
